version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    rules:
      - path: "_test.go"
        linters:
          - errcheck
          - gosec
          - goconst
          - unparam

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
