version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
        - gosec
        - goconst
        - unparam
