#!/bin/bash

# GitHub Actions Self-hosted Runner 簡易セットアップ
echo "==================================="
echo "Self-hosted Runner セットアップ"
echo "==================================="
echo ""
echo "このスクリプトは無料でUnity CI/CDを実現するための"
echo "ローカルランナーをセットアップします。"
echo ""
echo "必要なもの："
echo "1. Unity Hub + Unity 6000.1.14f1（インストール済み）"
echo "2. GitHub アカウント"
echo "3. このMacを常時起動しておく（CI実行時）"
echo ""
echo "セットアップ手順："
echo ""
echo "1. ブラウザで以下にアクセス："
echo "   https://github.com/kotahorii/merchant-tails/settings/actions/runners"
echo ""
echo "2. 'New self-hosted runner' をクリック"
echo ""
echo "3. macOS を選択"
echo ""
echo "4. 表示されるコマンドをコピーして実行"
echo ""
echo "5. Runnerの起動："
echo "   cd ~/actions-runner && ./run.sh"
echo ""
echo "メリット："
echo "- 完全無料"
echo "- Unity Personalライセンスが使える"
echo "- ビルド時間無制限"
echo ""
echo "デメリット："
echo "- Macを起動しておく必要がある"
echo "- 自宅のネット回線を使用"
echo ""