global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'merchant-tails'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Game metrics
  - job_name: 'merchant-tails-game'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Game metrics endpoint
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Grafana metrics (optional)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']