name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  GO_VERSION: "1.24"
  GODOT_VERSION: "4.4.1"
  PROTOC_VERSION: "25.1"

jobs:
  go-lint:
    name: Go Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache golangci-lint
        id: cache-golangci-lint
        uses: actions/cache@v4
        with:
          path: ~/go/bin/golangci-lint
          key: ${{ runner.os }}-golangci-lint-v2.3.1

      - name: Install golangci-lint
        if: steps.cache-golangci-lint.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ~/go/bin v2.3.1

      - name: Install dependencies
        run: |
          cd game
          go mod download

      - name: Cache lint results
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-cache-${{ hashFiles('game/**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-cache-

      - name: Run golangci-lint
        run: |
          cd game
          ~/go/bin/golangci-lint run

  go-test:
    name: Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/go/bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache test results
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-test
            game/.test-cache
          key: ${{ runner.os }}-go-test-${{ hashFiles('game/**/*.go', 'game/**/*_test.go') }}
          restore-keys: |
            ${{ runner.os }}-go-test-

      - name: Install dependencies
        run: |
          cd game
          go mod download

      - name: Cache Buf CLI
        id: cache-buf
        uses: actions/cache@v4
        with:
          path: ~/bin/buf
          key: ${{ runner.os }}-buf-latest

      - name: Install Buf CLI
        if: steps.cache-buf.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/bin
          curl -sSL "https://github.com/bufbuild/buf/releases/latest/download/buf-$(uname -s)-$(uname -m)" -o ~/bin/buf
          chmod +x ~/bin/buf
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Generate Protocol Buffers
        run: |
          cd game
          ~/bin/buf generate

      - name: Run tests
        run: |
          cd game
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./game/coverage.out
          flags: unittests
          name: codecov-umbrella

  godot-build:
    name: Godot Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Godot installation
        id: cache-godot
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/godot
            ~/.config/godot
            ~/godot
          key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false

      - name: Set up Go for GDExtension
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules and build
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-godot-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-godot-

      - name: Cache Godot project
        uses: actions/cache@v4
        with:
          path: |
            godot/.godot
            godot/.import
            godot/build
          key: ${{ runner.os }}-godot-project-${{ hashFiles('godot/**/*.tscn', 'godot/**/*.tres', 'godot/project.godot') }}
          restore-keys: |
            ${{ runner.os }}-godot-project-

      - name: Cache Protocol Buffers
        id: cache-protobuf
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/protoc
          key: ${{ runner.os }}-protobuf-${{ env.PROTOC_VERSION }}

      - name: Install Protocol Buffers
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Build GDExtension
        run: |
          if [ -f "Makefile" ]; then
            make build-go
          else
            echo "Makefile not found, skipping GDExtension build"
          fi

      - name: Import Godot project
        run: |
          if [ -f "godot/project.godot" ]; then
            godot --headless --quit --editor godot/project.godot
          else
            echo "Godot project not found, skipping import"
          fi

      - name: Run Godot tests
        run: |
          if [ -f "godot/project.godot" ]; then
            echo "Godot project found, but test mode not supported in this build"
            echo "Skipping Godot tests - requires custom build with tests=yes"
          else
            echo "Godot project not found, skipping tests"
          fi

  benchmark:
    name: Performance Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run benchmarks
        run: |
          cd game
          go test -bench=. -benchmem ./... | tee benchmark.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark-results
          path: game/benchmark.txt
          retention-days: 30

      - name: Display benchmark summary
        if: always()
        run: |
          echo "## Benchmark Results Summary"
          if [ -f game/benchmark.txt ]; then
            echo '```'
            head -50 game/benchmark.txt
            echo '```'
            echo ""
            echo "Full results available in workflow artifacts"
          else
            echo "No benchmark results found"
          fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    # Skip for dependabot PRs to avoid permission issues
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  docker-build:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./game
          file: ./game/Dockerfile
          push: false
          tags: merchant-tails:test
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      
      - name: Test Docker Compose
        run: |
          cd game
          docker compose -f docker-compose.dev.yml config
          docker compose -f docker-compose.yml config
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  documentation:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate Go documentation
        run: |
          go install golang.org/x/tools/cmd/godoc@latest
          cd game
          go list ./... | while read -r pkg; do
            go doc "$pkg" > /dev/null || true
          done
          echo "Documentation check completed"

      - name: Check documentation completeness
        run: |
          cd game
          echo "Checking for undocumented exports..."
          go list ./... | head -5 | while read -r pkg; do
            go doc "$pkg" | head -20 || true
          done
