name: Get Unity License for CI

on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: 'Unity version (leave empty to use project version)'
        required: false
        default: ''

jobs:
  get-license:
    name: Request Unity license file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create license request file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: ${{ github.event.inputs.unityVersion || '6000.1.14f1' }}

      - name: Upload license request file
        uses: actions/upload-artifact@v4
        with:
          name: Manual-Activation-File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 7

      - name: Print next steps
        run: |
          echo "## Next Steps to Get Unity License"
          echo ""
          echo "### For Unity Personal (Free) License:"
          echo ""
          echo "1. **Unity Hub Method (Recommended):**
          echo "   - Open Unity Hub on your local machine"
          echo "   - Sign in with your Unity ID"
          echo "   - Go to Preferences > Licenses"
          echo "   - Activate Personal license"
          echo "   - Find the license file at:"
          echo "     - macOS: ~/Library/Unity/Unity_v6000.x.ulf"
          echo "     - Windows: C:\\ProgramData\\Unity\\Unity_v6000.x.ulf"
          echo "     - Linux: ~/.local/share/unity3d/Unity/Unity_v6000.x.ulf"
          echo ""
          echo "2. **Docker Method (Alternative):**
          echo "   Run this command locally:"
          echo "   docker run -it --rm \\"
          echo "     -e UNITY_USERNAME='your-email@example.com' \\"
          echo "     -e UNITY_PASSWORD='your-password' \\"
          echo "     -v \$(pwd):/project \\"
          echo "     unityci/editor:6000.1.14f1-linux-il2cpp-2 \\"
          echo "     /bin/bash -c 'unity-editor -batchmode -quit -createManualActivationFile'"
          echo ""
          echo "3. **Self-hosted Runner (Best for Personal):**
          echo "   Use the self-hosted runner workflow instead"
          echo ""
          echo "### After Getting the License File:"
          echo "1. Copy the entire contents of the .ulf file"
          echo "2. Go to Settings > Secrets and variables > Actions"
          echo "3. Create a new secret named UNITY_LICENSE"
          echo "4. Paste the .ulf file contents"