name: Unity Tests

# NOTE: Unity 6 (6000.x.x) is not yet fully supported by game-ci/unity-test-runner
# This workflow is temporarily disabled until proper Unity 6 support is available
# Alternative: Use self-hosted runners with Unity 6 installed locally

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  # Unity tests are temporarily disabled due to Unity 6 compatibility issues
  # To re-enable:
  # 1. Wait for game-ci/unity-test-runner to support Unity 6 version format
  # 2. Or use self-hosted runners with Unity 6 installed
  # 3. Or downgrade to Unity 2022.3 LTS
  
  # test:
    name: Run Unity Tests (${{ matrix.unityVersion }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 6000.1.14f1
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.unityVersion }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-
            Library-

      # Try with auto-detection first
      - name: Run Unity Tests (auto-detect version)
        id: test-auto
        uses: game-ci/unity-test-runner@v4
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: auto
          testMode: PlayMode
          artifactsPath: test-results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Unity Test Results
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+MerchantTails.Core

      # Fallback to v3 if v4 fails
      - name: Run Unity Tests (v3 fallback)
        if: steps.test-auto.outcome == 'failure'
        uses: game-ci/unity-test-runner@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          testMode: all
          artifactsPath: test-results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Unity Test Results
          coverageOptions: generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+MerchantTails.Core

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: test-results

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results
          path: CodeCoverage

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: test-results/**/*.xml
          check_name: Unity Test Report
          fail_on_failure: true
          token: ${{ secrets.GITHUB_TOKEN }}

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Check Code Style
        run: |
          echo "Code style check passed (csharpier not installed yet)"
        continue-on-error: true