name: Acquire Unity License

on:
  workflow_dispatch:

jobs:
  acquire-license:
    name: Request manual Unity license file
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-manual-activation-file@v2
        with:
          unityVersion: 6000.1.14f1

      # Alternative: Try with Unity 2022.3 format
      - name: Request manual activation file (LTS format)
        if: failure()
        uses: game-ci/unity-request-manual-activation-file@v2
        with:
          unityVersion: 2022.3.45f1

      - name: Upload license request file
        uses: actions/upload-artifact@v4
        with:
          name: Manual-Activation-File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}