name: Unity CI/CD Pipeline (Self-hosted)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch: # 手動実行を許可

jobs:
  test:
    name: Test Unity Project
    runs-on: self-hosted  # ローカルマシンで実行
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Run Unity Tests
        run: |
          /Applications/Unity/Hub/Editor/6000.1.14f1/Unity.app/Contents/MacOS/Unity \
            -runTests \
            -batchmode \
            -projectPath . \
            -testPlatform ${{ matrix.testMode }} \
            -testResults test-results/${{ matrix.testMode }}-results.xml \
            -logFile -

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results (${{ matrix.testMode }})
          path: test-results

  build:
    name: Build Unity Project
    runs-on: self-hosted
    needs: test
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Build Unity Project
        run: |
          /Applications/Unity/Hub/Editor/6000.1.14f1/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -projectPath . \
            -buildTarget ${{ matrix.targetPlatform }} \
            -buildPath build/${{ matrix.targetPlatform }}/MerchantTails \
            -logFile -

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}