name: Acquire Unity License Activation File

on:
  workflow_dispatch:

jobs:
  request-manual-activation-file:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Request Manual Activation File
        id: getManualLicenseFile
        uses: game-ci/unity-request-manual-activation-file@v2
        with:
          unityVersion: 2022.3.10f1

      - name: Expose as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Manual-Activation-File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 7

      - name: Display activation instructions
        run: |
          echo "### Unity Personal License Activation Instructions"
          echo ""
          echo "1. Download 'Manual-Activation-File' artifact from this workflow run"
          echo "2. Visit https://license.unity3d.com/manual"
          echo "3. Upload the .alf file and log in with your Unity account"
          echo "4. Select 'Unity Personal' license type"
          echo "5. Download the generated Unity_v20xx.x.x.ulf license file"
          echo "6. Go to GitHub repository Settings > Secrets and variables > Actions"
          echo "7. Create a new secret named UNITY_LICENSE"
          echo "8. Paste the entire contents of the .ulf file as the value"
          echo ""
          echo "After completing these steps, the Unity Tests workflow will be able to run."
          echo ""
          echo "For more details: https://game.ci/docs/github/activation"