name: Unity Tests (Docker)

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-docker:
    name: Unity Tests via Docker
    runs-on: ubuntu-latest
    container:
      # Use Unity Hub docker image that supports Unity 6
      image: unityci/editor:ubuntu-6000.1.14f1-linux-il2cpp-3
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Unity license
        run: |
          echo "${{ secrets.UNITY_LICENSE_CONTENT }}" > Unity_lic.ulf
          mkdir -p /root/.local/share/unity3d/Unity/
          cp Unity_lic.ulf /root/.local/share/unity3d/Unity/Unity_lic.ulf

      - name: Run PlayMode Tests
        run: |
          unity-editor \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile - \
            -projectPath . \
            -runTests \
            -testPlatform PlayMode \
            -testResults test-results/playmode-results.xml \
            -coverageResultsPath CodeCoverage \
            -coverageOptions "generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+MerchantTails.*"

      - name: Run EditMode Tests
        run: |
          unity-editor \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile - \
            -projectPath . \
            -runTests \
            -testPlatform EditMode \
            -testResults test-results/editmode-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: test-results

      - name: Upload Coverage Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Coverage results
          path: CodeCoverage

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: test-results/**/*.xml
          check_name: Unity Test Report
          fail_on_failure: true