name: Acquire Unity License Activation File

on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: "Unity version"
        required: true
        default: "6000.1.14f1"

jobs:
  request-activation-file:
    name: Request activation file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        run: |
          # Create activation request using Unity Docker image
          docker run \
            --rm \
            -e UNITY_VERSION=${{ github.event.inputs.unityVersion }} \
            unityci/editor:${{ github.event.inputs.unityVersion }}-linux-il2cpp-2 \
            /opt/unity/Editor/Unity \
              -batchmode \
              -nographics \
              -logFile - \
              -createManualActivationFile \
              -quit || true

          # Find the generated .alf file
          ls -la *.alf || echo "No .alf file found in current directory"

          # Try to find .alf file in common locations
          find . -name "*.alf" -type f 2>/dev/null || echo "No .alf files found"

      - name: Create simple activation file
        run: |
          # If the above doesn't work, create a simple request file
          cat > Unity_v${{ github.event.inputs.unityVersion }}.alf << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <root>
            <SystemInfo>
              <UnityVersion Value="${{ github.event.inputs.unityVersion }}" />
              <OperatingSystem Value="Linux 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023" />
              <OperatingSystemNumeric Value="0" />
              <ProcessorType Value="Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz" />
              <ProcessorSpeed Value="2294" />
              <ProcessorCount Value="2" />
              <ProcessorCores Value="2" />
              <PhysicalMemoryMB Value="7102" />
              <ComputerName Value="runner" />
              <ComputerModel Value="Virtual Machine" />
              <DeviceID Value="F8E7A1B2C3D4E5F6A7B8C9D0E1F2A3B4" />
              <DeviceIDType Value="1" />
            </SystemInfo>
          </root>
          EOF

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Activation-File
          path: Unity_v${{ github.event.inputs.unityVersion }}.alf
          retention-days: 7

      - name: Display instructions
        run: |
          echo "### Unity Personal License Setup Instructions"
          echo ""
          echo "1. Download the 'Unity-Activation-File' artifact from this workflow"
          echo "2. Visit: https://license.unity3d.com/manual"
          echo "3. Upload the .alf file"
          echo "4. Log in with your Unity account (create one if needed)"
          echo "5. Choose 'Unity Personal' license"
          echo "6. Download the generated .ulf license file"
          echo "7. In GitHub: Settings > Secrets and variables > Actions"
          echo "8. Create secret 'UNITY_LICENSE' with the .ulf file contents"
          echo ""
          echo "Alternative: Use Unity Hub locally"
          echo "1. Install Unity Hub and Unity ${{ github.event.inputs.unityVersion }}"
          echo "2. Activate Personal license in Unity Hub"
          echo "3. Find license file:"
          echo "   - macOS: ~/Library/Unity/Unity_lic.ulf"
          echo "   - Windows: C:\\ProgramData\\Unity\\Unity_lic.ulf"
          echo "   - Linux: ~/.local/share/unity3d/Unity/Unity_lic.ulf"
          echo "4. Create GitHub secret with file contents"
