name: Unity CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  test:
    name: Test Unity Project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
        unityVersion:
          - 2022.3.21f1
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Git LFS checkout
      - name: Checkout LFS objects
        run: git lfs checkout

      # Cache Unity Library folder
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.unityVersion }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-
            Library-

      # Unity Test Runner
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        id: unity-tests
        with:
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: test-results
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Unity Test Results (${{ matrix.testMode }})

      # Upload test results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results (${{ matrix.testMode }})
          path: test-results

      # Publish test results
      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unity Test Results (${{ matrix.testMode }})
          path: test-results/*.xml
          reporter: java-junit
          fail-on-error: true

  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Git LFS checkout
      - name: Checkout LFS objects
        run: git lfs checkout

      # Cache Unity Library folder
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-2022.3.21f1-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-2022.3.21f1-
            Library-

      # Unity Build
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.21f1
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: MerchantTails
          buildsPath: build
          buildMethod: BuildScript.BuildGame

      # Upload build artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup .NET for code analysis
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      # Install code analysis tools
      - name: Install dotnet tools
        run: |
          dotnet tool install --global dotnet-format
          dotnet tool install --global csharpier

      # Run code formatting check
      - name: Check code formatting
        run: |
          dotnet format --verify-no-changes --verbosity diagnostic Assets/Scripts/

      # Run code style check with csharpier
      - name: Check code style
        run: |
          csharpier --check Assets/Scripts/
        continue-on-error: true

  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # Git LFS checkout
      - name: Checkout LFS objects
        run: git lfs checkout

      # Cache Unity Library folder
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-2022.3.21f1-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-2022.3.21f1-
            Library-

      # Run performance tests
      - name: Run Performance Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 2022.3.21f1
          testMode: PlayMode
          customParameters: -testCategory "Performance"
          artifactsPath: performance-results

      # Upload performance test results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Performance Test Results
          path: performance-results

  # Steam deployment disabled - will be enabled when ready for release
  # deploy:
  #   name: Deploy to Steam (Production)
  #   runs-on: ubuntu-latest
  #   needs: [test, build, code-quality]
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   steps:
  #     # Checkout repository
  #     - uses: actions/checkout@v4
  #
  #     # Download build artifacts
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: Build-StandaloneWindows64
  #         path: build/windows
  #
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: Build-StandaloneLinux64
  #         path: build/linux
  #
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: Build-StandaloneOSX
  #         path: build/mac
  #
  #     # Deploy to Steam (will be implemented when ready)
  #     - name: Deploy to Steam
  #       run: |
  #         echo "Steam deployment will be implemented here"

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [test, build, code-quality, performance-test]
    if: always()
    steps:
      - name: Notify Success
        if: needs.test.result == 'success' && needs.build.result == 'success'
        run: |
          echo "✅ All tests passed and build succeeded!"
          echo "Test Results: ${{ needs.test.result }}"
          echo "Build Results: ${{ needs.build.result }}"
          echo "Code Quality: ${{ needs.code-quality.result }}"
          echo "Performance: ${{ needs.performance-test.result }}"

      - name: Notify Failure
        if: needs.test.result == 'failure' || needs.build.result == 'failure'
        run: |
          echo "❌ Tests failed or build failed!"
          echo "Test Results: ${{ needs.test.result }}"
          echo "Build Results: ${{ needs.build.result }}"
          exit 1
